version: "3.9"

name: bank-system

networks:
  bank-net:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data
      - ../docker/postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - bank-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bankdb"]
      interval: 10s
      timeout: 5s
      retries: 15


  bank-account-service:
    build: ../services/account-service
    container_name: bank-account-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accountdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_started
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 15

  bank-auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    container_name: bank-auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_started
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 15

  bank-transaction-service:
    build: ../services/transaction-service
    container_name: bank-transaction-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transactiondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVICES_ACCOUNT_BASE_URL: http://bank-account-service:8080

    depends_on:
      postgres:
        condition: service_healthy
      bank-account-service:
        condition: service_started
      prometheus:
        condition: service_started
    networks:
      - bank-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 20s
      timeout: 5s
      retries: 15

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: bank-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - bank_prometheus_data:/prometheus
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank-net

  grafana:
    image: grafana/grafana:10.4.5
    container_name: bank-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - bank_grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - bank-net

volumes:
  bank_postgres_data:
  bank_prometheus_data:
  bank_grafana_data:
