version: "3.9"

name: bank-system

services:
  # Shared database for local dev (you can split by service later if you want)
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data
      - ../docker/postgres/init:/docker-entrypoint-initdb.d:ro

  # Prometheus (metrics collector)
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: bank-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - bank_prometheus_data:/prometheus
    depends_on:
      - postgres

  # Grafana (dashboards)
  grafana:
    image: grafana/grafana:10.4.5
    container_name: bank-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - bank_grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  account-service:
    build: ../services/account-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accountdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

volumes:
  bank_postgres_data:
  bank_prometheus_data:
  bank_grafana_data:
