global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "account-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["account-service:8080"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "transaction-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["transaction-service:8082"]
